### ISSUE TITLE
Cant see stats for sidekiq

### ISSUE THREAD

**Issue by AbdullahMuhammad** [bsm/sidekiq-datadog#1]
Hi i added your gem and followed your instructions. But i cant see sidekiq in my dashboard.
Can you please guide me whats wrong.

**Comment by dim** [comment]
Are you running dd-agent with statsd service? Have you passed the right options to the middleware? The defaults may not be appropriate: http://www.rubydoc.info/gems/sidekiq-datadog/Sidekiq%2FMiddleware%2FServer%2FDatadog%3Ainitialize
