### ISSUE TITLE
NameError: uninitialized constant Sidekiq::Process::CLOCK_MONOTONIC

### ISSUE THREAD

**Issue by keithbro** [bsm/sidekiq-datadog#16]
New code released recently (https://github.com/bsm/sidekiq-datadog/pull/13) should reference `::Process::CLOCK_MONOTONIC` instead of `Process::CLOCK_MONOTONIC` otherwise it will use `Sidekiq::Process` and result in the `uninitialized constant` error.

**Comment by dim** [comment]
Thanks, see #15
