### ISSUE TITLE
include tracking sidekiq thread usage count?

### ISSUE THREAD

**Issue by dfuentes77** [bsm/sidekiq-datadog#24]
Does it make sense to also track thread usage count by getting `concurrency` and `busy` from process and sending those to datadog as well?  Simple example here:
https://stackoverflow.com/a/38470260

I think this could be valuable for knowing capacity usage and trending in Datadog dashboards, and doing accurate capacity planning for scale.

**Comment by dim** [comment]
@dfuentes77 would you mind providing a quick PR for that?
