### ISSUE TITLE
NameError when using sidekiq-datadog and sidekiq-pro

### ISSUE THREAD

**Issue by weijenlarryli** [bsm/sidekiq-datadog#25]
I am upgrading to Rails 6, and I use both sidekiq-pro (5.3.0) and sidekiq-datadog (0.6.0).
And I get a NameError about Datadog::Statsd in sidekiq-pro, because it does not have "::" before Datadog::Statsd.

What I have is having both sidekiq-pro and sidekiq-datadog in my gem.
And my code looks like this:

```
require 'datadog/statsd'
Sidekiq::Pro.dogstatsd = -> { ::Datadog::Statsd.new }
config.server_middleware do |chain|
  chain.add Sidekiq::Middleware::Server::Datadog
end
```

The error is 
`NameError: uninitialized constant Sidekiq::Datadog::Statsd`

Is there a way to fix this or I cannot use both sidekiq-pro and sidekiq-datadog?

**Comment by dim** [comment]
@dmagliola would be be able to help?
