### ISSUE TITLE
queued_ms also includes the time jobs sit in the retry queue

### ISSUE THREAD

**Issue by nilbus** [bsm/sidekiq-datadog#6]
> When a job has an error and is retried, potentially with exponential backoff, computing from created_at will include those retries and backoff periods as part of the queued_ms. Which is not an actual indication of how long the job was waiting in a queue ready to execute.
—@vietord

On 0.3.3, I am still experiencing this problem. I see large/growing `queued_ms` times when a queue is primarily working retries.
![image](https://cloud.githubusercontent.com/assets/64751/21598711/65c6a87e-d12f-11e6-894a-1bd3bc80cdd0.png)
During these periods, the sidekiq web interface shows 0 jobs enqueued on the queue, 0 jobs running on workers assigned to that queue, and retries scheduled.

I think #3 improved the `queued_ms` metric, but the same issue still exists: part of the retry time is included in a metric that ought to indicate how long something was sitting in a queue waiting for a worker to pick it up.

Check out these values for a job that's being retried in one of my queues. Note that the `enqueued_at` time is equal to the last retry time. The `created_at` time would also be much earlier, since this is the 23rd retry and we've backed off to a 4 month interval.
![Enqueued time and Last Retry are both 28 days ago](https://cloud.githubusercontent.com/assets/64751/21596459/72edb306-d109-11e6-98cf-bbd4f74c6fe9.png)

If we use `job.at` (next retry) when set and `enqueued_at` otherwise, then I think we'll get that "how long has it been sitting eligible to run, waiting for a worker" metric that we're looking for. I wanted to run this buy you all before creating a PR. Do you agree with the conclusion I came to?

**Comment by dim** [comment]
Thanks for the explanation, makes sense. Looking forward to the PR, I will close this one for now.

**Comment by nilbus** [comment]
I now realize that `job.at` is a calculated value based on the retry count and last retry, and it's not a value provided in the job hash. I'm asking Mike Perham whether he has any advice on how to calculate that value in this middleware.

**Comment by nilbus** [comment]
> Unfortunately the `at` parameter is not surfaced during runtime when scheduling and enqueuing jobs internally.  It’s only exposed when introspecting the scheduled sets via the API.
>
> FWIW if it were my project, I would simply skip retries when calculating the enqueued delay.  Ideally retries are a small fraction of the overall job flow.
—Mike Perham

Unless you object (then let's discuss), I'll move forward with a pull request that excludes retries (and scheduled jobs?) that bloat the enqueued time.

/cc @qgriffith

**Comment by dim** [comment]
No, feel free to go ahead

**Comment by nilbus** [comment]
@qgriffith We can check for the presence of a `failed_at` key to determine if it’s a retry. Scheduled jobs have an `at` key. We can exclude jobs that have either of these keys.
