### ISSUE TITLE
Access job count in queue?

### ISSUE THREAD

**Issue by chadwilken** [bsm/sidekiq-datadog#9]
Is there a way to see how many jobs are currently queued? I would like to add a monitor for the number of jobs in a queue to make sure it doesn't get too high.

**Comment by dim** [comment]
It's unfortunately not something we can report from the library directly, as it requires access to the Sidekiq client (rather being a simple server middleware). That said, you can just setup a minutely job to query sidekiq for the length of your queues and update datadog manually via `statsd = ::Datadog::Statsd.new(host, port)`. See https://github.com/mperham/sidekiq/wiki/API
